# Generated by Django 4.1.2 on 2023-06-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
